defaults: &defaults
  working_directory: ~/pronto-praise
  docker:
    - image: circleci/python:3.6.1

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  python_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
          - py-deps-{{ checksum "requirements/local.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/local.txt
      - save_cache:
          key: py-deps-{{ checksum "requirements/local.txt" }}
          paths:
            - ./venv

  static_analysis:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
          - py-deps-{{ checksum "requirements/local.txt" }}
      - run:
          name: Run Static Analysis
          command: |
            . venv/bin/activate
            cd pronto_praise
            flake8

  unit_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
          - py-deps-{{ checksum "requirements/local.txt" }}
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            cd pronto_praise
            python manage.py test

  deploy:
    <<: *defaults
    steps:
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "SHA256:PFBY/vsdxe/e4uclGYaRwWuk0/AeYZGi/3RWv46D56s zkan@Kans-MacBook-Pro.local"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master
            fi

workflows:
  version: 2
  pronto_praise_pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - static_analysis:
          requires:
            - python_dependencies
      - unit_tests:
          requires:
            - python_dependencies
      - deploy:
          requires:
            - static_analysis
            - unit_tests
